name: ci
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile || pnpm install
      # Tolérants pendant le bootstrap
      - name: Lint
        run: pnpm lint || true
      - name: Build
        run: pnpm build || true
      - name: Test
        run: pnpm test || true
